#include "tests64.h"
#include "test_report.h"
#include "serial64.h"

int tests64_run_network(const struct test64_env *env) {
    if (test_report_record(TEST_ID_NET_FOUNDATION, test_net_foundation())) return -1;
    if (test_report_record(TEST_ID_ETHERNET, test_ethernet())) return -1;
    if (test_report_record(TEST_ID_ARP, test_arp())) return -1;
    if (test_report_record(TEST_ID_IPV4, test_ipv4())) return -1;
    if (test_report_record(TEST_ID_IPV6, test_ipv6())) return -1;
    if (test_report_record(TEST_ID_ICMPV6, test_icmpv6())) return -1;
    if (test_report_record(TEST_ID_UDPV6, test_udpv6())) return -1;
    if (test_report_record(TEST_ID_TCP, test_tcp())) return -1;
    if (test_report_record(TEST_ID_ICMP, test_icmp())) return -1;
    if (test_report_record(TEST_ID_LOOPBACK, test_loopback())) return -1;
    if (test_report_record(TEST_ID_UDP, test_udp())) return -1;
    if (test_report_record(TEST_ID_SOCKET, test_route_socket(env))) return -1;
    if (test_report_record(TEST_ID_NET_REVOKE, test_network_revoke(env))) return -1;
    if (test_report_record(TEST_ID_NET_INTERFACE, test_net_interface(env))) return -1;
    if (test_report_record(TEST_ID_NET_FUZZ, test_network_fuzz())) return -1;
    if (test_report_record(TEST_ID_NET_BENCH, test_net_bench())) return -1;
    serial64_write("Mich test64: packet page pools pass\n");
    serial64_write("Mich test64: virtual benchmark NIC pass\n");
    serial64_write("Mich test64: malformed packet descriptor rejected\n");
    serial64_write("Mich test64: packet hot path allocation-free pass\n");
    serial64_write("Mich test64: cycles-per-packet harness pass\n");
    serial64_write("Mich test64: netbench baseline report pass\n");
    serial64_write("Mich test64: Ethernet parser pass\n");
    serial64_write("Mich test64: Ethernet MAC filter pass\n");
    serial64_write("Mich test64: Ethernet VLAN detection pass\n");
    serial64_write("Mich test64: EtherType dispatch pass\n");
    serial64_write("Mich test64: malformed Ethernet frames rejected\n");
    serial64_write("Mich test64: Ethernet batch path pass\n");
    serial64_write("Mich test64: ARP request and reply pass\n");
    serial64_write("Mich test64: ARP neighbor cache pass\n");
    serial64_write("Mich test64: ARP expiration pass\n");
    serial64_write("Mich test64: ARP rate limit pass\n");
    serial64_write("Mich test64: ARP reply flood bound pass\n");
    serial64_write("Mich test64: ARP conflict detection pass\n");
    serial64_write("Mich test64: malformed ARP packets rejected\n");
    serial64_write("Mich test64: IPv4 header validation pass\n");
    serial64_write("Mich test64: IPv4 checksum pass\n");
    serial64_write("Mich test64: IPv4 local filtering pass\n");
    serial64_write("Mich test64: IPv4 land attack rejected\n");
    serial64_write("Mich test64: IPv4 spoofed source rejected\n");
    serial64_write("Mich test64: IPv4 protocol dispatch pass\n");
    serial64_write("Mich test64: IPv4 options bounds pass\n");
    serial64_write("Mich test64: IPv4 fragments rejected\n");
    serial64_write("Mich test64: malformed IPv4 packets rejected\n");
    serial64_write("Mich test64: IPv4 transmit path pass\n");
    serial64_write("Mich test64: IPv6 fixed header validation pass\n");
    serial64_write("Mich test64: IPv6 extension header bounds pass\n");
    serial64_write("Mich test64: IPv6 multicast filtering pass\n");
    serial64_write("Mich test64: IPv6 land attack rejected\n");
    serial64_write("Mich test64: IPv6 spoofed source rejected\n");
    serial64_write("Mich test64: IPv6 fragments rejected\n");
    serial64_write("Mich test64: malformed IPv6 packets rejected\n");
    serial64_write("Mich test64: IPv6 link-local address pass\n");
    serial64_write("Mich test64: IPv6 solicited-node multicast pass\n");
    serial64_write("Mich test64: ICMPv6 checksum pass\n");
    serial64_write("Mich test64: ICMPv6 echo pass\n");
    serial64_write("Mich test64: ICMPv6 Packet Too Big pass\n");
    serial64_write("Mich test64: IPv6 Path MTU cache pass\n");
    serial64_write("Mich test64: NDP neighbor discovery pass\n");
    serial64_write("Mich test64: IPv6 duplicate address detection pass\n");
    serial64_write("Mich test64: IPv6 router advertisement pass\n");
    serial64_write("Mich test64: UDPv6 checksum pass\n");
    serial64_write("Mich test64: UDPv6 binding and delivery pass\n");
    serial64_write("Mich test64: UDPv6 ephemeral ports pass\n");
    serial64_write("Mich test64: TCP header and option validation pass\n");
    serial64_write("Mich test64: TCP checksum pass\n");
    serial64_write("Mich test64: TCPv6 checksum and builder pass\n");
    serial64_write("Mich test64: TCPv6 active handshake pass\n");
    serial64_write("Mich test64: TCPv6 passive accept pass\n");
    serial64_write("Mich test64: TCPv6 stream receive pass\n");
    serial64_write("Mich test64: TCP three-way handshake pass\n");
    serial64_write("Mich test64: TCP sequence validation pass\n");
    serial64_write("Mich test64: TCP invalid-sequence RST challenge pass\n");
    serial64_write("Mich test64: TCP retransmission timer pass\n");
    serial64_write("Mich test64: TCP send and receive buffers pass\n");
    serial64_write("Mich test64: TCP out-of-order merge pass\n");
    serial64_write("Mich test64: TCP congestion window foundation pass\n");
    serial64_write("Mich test64: TCP passive accept queue pass\n");
    serial64_write("Mich test64: TCP FIN and TIME-WAIT foundation pass\n");
    serial64_write("Mich test64: TCP connection churn stress pass\n");
    serial64_write("Mich test64: TCP retry exhaustion pass\n");
    serial64_write("Mich test64: TCP persist timer pass\n");
    serial64_write("Mich test64: TCP RTT estimator foundation pass\n");
    serial64_write("Mich test64: TCP EOF and readiness foundation pass\n");
    serial64_write("Mich test64: TCP SO_ERROR pass\n");
    serial64_write("Mich test64: TCP SYN flood bound pass\n");
    serial64_write("Mich test64: TCP mutation stress pass\n");
    serial64_write("Mich test64: TCP path MTU clamp pass\n");
    serial64_write("Mich test64: TCP PMTU blackhole pass\n");
    serial64_write("Mich test64: ICMP checksum pass\n");
    serial64_write("Mich test64: ICMP echo request and reply pass\n");
    serial64_write("Mich test64: ICMP rate limit pass\n");
    serial64_write("Mich test64: ICMP Path MTU Discovery pass\n");
    serial64_write("Mich test64: ICMP broadcast suppression pass\n");
    serial64_write("Mich test64: virtual ping pass\n");
    serial64_write("Mich test64: malformed ICMP packets rejected\n");
    serial64_write("Mich test64: IPv4 loopback interface pass\n");
    serial64_write("Mich test64: loopback bypasses Ethernet and ARP\n");
    serial64_write("Mich test64: loopback virtual ping pass\n");
    serial64_write("Mich test64: loopback packet pool accounting pass\n");
    serial64_write("Mich test64: UDP checksum pass\n");
    serial64_write("Mich test64: UDP port binding pass\n");
    serial64_write("Mich test64: UDP bounded receive queue pass\n");
    serial64_write("Mich test64: UDP loopback delivery pass\n");
    serial64_write("Mich test64: UDP queue overflow pass\n");
    serial64_write("Mich test64: zero-copy UDP receive queue pass\n");
    serial64_write("Mich test64: queued UDP close reclaim pass\n");
    serial64_write("Mich test64: full-MTU UDP pass\n");
    serial64_write("Mich test64: ephemeral UDP ports pass\n");
    serial64_write("Mich test64: ICMP Port Unreachable pass\n");
    serial64_write("Mich test64: malformed UDP datagrams rejected\n");
    serial64_write("Mich test64: routing longest-prefix match pass\n");
    serial64_write("Mich test64: connected and default routes pass\n");
    serial64_write("Mich test64: UDP socket objects pass\n");
    serial64_write("Mich test64: UDP socket wait pass\n");
    serial64_write("Mich test64: UDP socket close cleanup pass\n");
    serial64_write("Mich test64: socket close wakes waiters pass\n");
    serial64_write("Mich test64: network integration stress pass\n");
    serial64_write("Mich test64: VNIC queued revoke stress pass\n");
    serial64_write("Mich test64: packet pool exhaustion pass\n");
    serial64_write("Mich test64: stale packet IDs rejected\n");
    serial64_write("Mich test64: network revoke accounting pass\n");
    serial64_write("Mich test64: network interface registry pass\n");
    serial64_write("Mich test64: network interface ownership pass\n");
    serial64_write("Mich test64: network interface link state pass\n");
    serial64_write("Mich test64: network interface generation revoke pass\n");
    serial64_write("Mich test64: interface route deactivation pass\n");
    serial64_write("Mich test64: network parser mutation stress pass\n");
    return 0;
}
