#!/bin/sh
set -eu

# Emit the kernel header that carries the primary capsule's sole test ud2 address.
# The link address is decided by whatever toolchain built the capsule, so it is
# extracted here instead of hardcoded in the kernel, where a literal silently
# rots across compilers (and cannot survive the s390x port).

capsule=${1:?capsule required}
objdump=${OBJDUMP:-objdump}

addresses=$("$objdump" -d "$capsule" | awk '
$2 == "0f" && $3 == "0b" {
    address = $1
    sub(/:$/, "", address)
    print "0x" address
}')
[ -n "$addresses" ] || {
    echo "virtio recovery rip: primary capsule has no ud2" >&2
    exit 1
}
[ "$(printf '%s\n' "$addresses" | wc -l | tr -d '[:space:]')" -eq 1 ] || {
    echo "virtio recovery rip: primary capsule has multiple ud2 instructions" >&2
    exit 1
}

cat <<EOF
// Auto-generated by scripts/gen-virtio-net-recovery-rip.sh. Do not edit.
// Link address of the primary capsule's sole test ud2, read from the compiled
// capsule so the kernel recovery catalog matches whatever toolchain built it.
#ifndef VIRTIO_NET_RECOVERY_RIP_H
#define VIRTIO_NET_RECOVERY_RIP_H
#define VIRTIO_NET_RECOVERY_TEST_RIP ${addresses}ULL
#endif
EOF
